#!/bin/bash

echo TASTE Data View Convertor - From ASN.1 to AADLV2

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi
INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"


# User may pass several ASN.1 files as parameters
for f in $@
do
    # Ignore taste internal ASN.1 files
    name=$(basename "$f")
    if [ "$name" != taste-types.asn -a "$name" != __ExtraTypes.asn ]
    then
        if [ ! -f "$f" ]
        then
            echo -e "${INFO} File not found: ${f}"
            exit 1
        else
            echo -e "${INFO} Using file: ${f}"
            filename=$(readlink -e "$f")
            DATAVIEW+="$filename "
            acnfile=$(readlink -e "${f%.*}.acn")
            if [ -f "$acnfile" ]
            then
                echo -e "${INFO} Using ACN file: ${acnfile}"
                DATAVIEW+="$acnfile "
            fi
        fi
    fi
done

# If DATAVIEW string is empty, check for DataView.asn in current folder
if [ -z "$(echo -n $DATAVIEW)" ]
then
    if [ -f DataView.asn ]
    then
        echo -e "${INFO} Using file: DataView.asn"
        DATAVIEW=$(readlink -e DataView.asn)
    else
        >&2 echo -e "${ERROR} No data view found"
        echo -e "${INFO} Usage: taste-update-data-view <set of ASN.1 files>"
        exit 1
    fi
    if [ -f DataView.acn ]
    then
        echo -e "${INFO} Using file: DataView.acn"
        DATAVIEW+=" $(readlink -e DataView.acn)"
    fi
fi

#AADL=${DATAVIEW%.*}.aadl
AADL=DataView.aadl

if [ -f __ExtraTypes.asn ]
then
    echo -e "${INFO} Using file: __ExtraTypes.asn"
    DATAVIEW+=" $(readlink -e "__ExtraTypes.asn")"
fi

if [ -f __ExtraTypes.acn ]
then
    echo -e "${INFO} Using file: __ExtraTypes.acn"
    DATAVIEW+=" $(readlink -e "__ExtraTypes.acn")"
fi

DATAVIEW+=" $(taste-config --prefix)/share/taste-types/taste-types.asn"

# can asn2aadlPlus with a call to uniq to filter out duplicate outputs
# due to multiple calls to the ASN.1 compiler
#asn2aadlPlus $DATAVIEW "$AADL" -aadlv2 2>&1 | uniq >&2
asn2aadlPlus $DATAVIEW "$AADL" -aadlv2 2>&1 > >(uniq >&2)

if [ "$?" = "1" ]
then
    >&2 echo -e "${ERROR} Impossible to convert the dataview from ASN.1 to AADL"
    echo -e "${INFO} Command: asn2aadlPlus ${DATAVIEW} ${AADL} -aadlv2"
    exit 1
else
    echo -e "${INFO} All OK"
    exit 0
fi

