#!/bin/bash
if [ -f InterfaceView.aadl ]
then
    echo 'Opening TASTE project'
    INTERFACEVIEW=InterfaceView.aadl
else
    echo Error: missing InterfaceView.aadl
    echo First use taste-create-project to start a new project
    exit 1
fi

grep -i taste-directives.aadl "$INTERFACEVIEW" >/dev/null && {
    echo Your interface view needs to be upgraded\!
    echo Please upgrade it with:
    echo
    echo "  taste-upgrade-IF-view oldIFview newIFview"
    echo
    echo ...and use the newIFview instead.
    exit 1
}

echo TASTE Project Editor - Use only the SAVE button - not \"Save as..\" !

# If there is no deployment view, only load interface view
EXTRA_CMD=
if [ ! -f DeploymentView.aadl ]
then
    EXTRA_CMD+=--load-interface-view
    EXTRA_CMD+=' InterfaceView.aadl' 
    EXTRA_CMD+=' --aadl-library $(taste-config --prefix)/share/ocarina/AADLv2/ocarina_components.aadl'
else
    EXTRA_CMD=
fi
echo TASTE $EXTRA_CMD --data-view DataView.aadl --load-deployment-view DeploymentView.aadl
TASTE $EXTRA_CMD --data-view DataView.aadl --load-deployment-view DeploymentView.aadl
