#!/bin/bash

if [ -t 1 ]
then
    COLORON="\e[1m\e[32m"
    REDCOLORON="\e[1m\e[31m"
    COLOROFF="\e[0m"
else
    COLORON=""
    REDCOLORON=""
    COLOROFF=""
fi

INFO="${COLORON}[INFO]${COLOROFF}"
ERROR="${REDCOLORON}[ERROR]${COLOROFF}"

if [ -f InterfaceView.aadl ]
then
    echo -e "${INFO} Opening TASTE project"
    INTERFACEVIEW=InterfaceView.aadl
else
    echo -e "${ERROR} Missing InterfaceView.aadl"
    echo -e "${ERROR} First use taste-create-project to start a new project"
    exit 1
fi

grep -i taste-directives.aadl "$INTERFACEVIEW" >/dev/null && {
    echo -e "${ERROR} Your interface view needs to be upgraded\!"
    echo "   Please upgrade it with:"
    echo
    echo "      taste-upgrade-IF-view oldIFview newIFview"
    echo
    echo "   ...and use the newIFview instead."
    exit 1
}

# If there is no deployment view, only load interface view
EXTRA_CMD=
if [ ! -f DeploymentView.aadl ]
then
    EXTRA_CMD+=--load-interface-view
    EXTRA_CMD+=' InterfaceView.aadl' 
    EXTRA_CMD+=" --aadl-library $(taste-config --prefix)/share/ocarina/AADLv2/ocarina_components.aadl "
else
    # Update path to Ocarina Components in the deployment view
    sed -i "s,HWLibraries.*,HWLibraries => (\"$(taste-config --prefix)/share/ocarina/AADLv2/ocarina_components.aadl\");," DeploymentView.aadl 
    EXTRA_CMD+=' --load-deployment-view DeploymentView.aadl '
fi

# Add the components from the components library
FIRST=1
LIBDIR=$(taste-config --prefix)/share/components_library
for each in $LIBDIR/*
do
    if [ $FIRST -eq 1 ]
    then
        EXTRA_CMD+='--edit-aadl '
    else
        EXTRA_CMD+=,
    fi
    EXTRA_CMD+=$each/interfaceview.aadl
    FIRST=0
done

EXTRA_CMD+=' --update-properties ConcurrencyView_Properties.aadl '


echo -e "${INFO} Running
    TASTE $EXTRA_CMD
"
TASTE $EXTRA_CMD
